/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_example_Happy */

#ifndef _Included_org_example_Happy
#define _Included_org_example_Happy
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_example_Happy
 * Method:    printText
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_example_Happy_printText
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
